obstacle_range: 2.5
raytrace_range: 3.0
# the car is 53.4 cm x 29 cm
footprint: [[-0.145, -0.27], [-0.145, 0.27], [0.145, 0.27], [0.145, -0.27]]
inflation_radius: 0.5

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: /base_link_laser, data_type: LaserScan, topic: /sensors/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
